name = "mergit"
main = "src/index.js"
compatibility_date = "2024-02-01"

# Text file imports (for HTML and JS)
[[rules]]
type = "Text"
globs = ["**/*.html"]
fallthrough = true

[[rules]]
type = "Text"
globs = ["**/pdf-lib.min.js"]
fallthrough = true

# Binary file imports (for images)
[[rules]]
type = "Data"
globs = ["**/*.png"]
fallthrough = true
